### ISSUE TITLE
Can't open the snailbox in server

### ISSUE THREAD

**Issue by FinDreammm** [itsmeowCommissions/SnailMail#4]
https://paste.ubuntu.com/p/CSZWCynB39/

**Comment by itsmeow** [comment]
I cannot access this log. Please paste somewhere else or put directly here.

**Comment by itsmeow** [comment]
Paste contents:

```
月2021 11:31:01.606] [Thread-52/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.IllegalStateException: InventoryOpenEvent cannot be triggered asynchronously from another thread.
[16七月2021 11:31:01.607] [Thread-52/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:572)
[16七月2021 11:31:01.609] [Thread-52/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactoryMixin.java:1163)
[16七月2021 11:31:01.611] [Thread-52/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactoryMixin.java:1149)
[16七月2021 11:31:01.614] [Thread-52/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.network.NetworkHooks.handler$bnm000$arclight$openContainer(NetworkHooksMixin.java:533)
[16七月2021 11:31:01.615] [Thread-52/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.network.NetworkHooks.openGui(NetworkHooksMixin.java:225)
[16七月2021 11:31:01.617] [Thread-52/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at dev.itsmeow.snailmail.block.entity.SnailBoxBlockEntity.lambda$openGUI$2(SnailBoxBlockEntity.java:162)
[16七月2021 11:31:01.619] [Thread-52/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Thread.run(Thread.java:748)
[16七月2021 11:31:03.346] [Thread-53/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.IllegalStateException: InventoryOpenEvent cannot be triggered asynchronously from another thread.
[16七月2021 11:31:03.347] [Thread-53/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:572)
[16七月2021 11:31:03.349] [Thread-53/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactoryMixin.java:1163)
[16七月2021 11:31:03.351] [Thread-53/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactoryMixin.java:1149)
[16七月2021 11:31:03.353] [Thread-53/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.network.NetworkHooks.handler$bnm000$arclight$openContainer(NetworkHooksMixin.java:533)
[16七月2021 11:31:03.355] [Thread-53/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.network.NetworkHooks.openGui(NetworkHooksMixin.java:225)
[16七月2021 11:31:03.357] [Thread-53/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at dev.itsmeow.snailmail.block.entity.SnailBoxBlockEntity.lambda$openGUI$2(SnailBoxBlockEntity.java:162)
[16七月2021 11:31:03.359] [Thread-53/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Thread.run(Thread.java:748)
[16七月2021 11:31:03.687] [Thread-54/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.IllegalStateException: InventoryOpenEvent cannot be triggered asynchronously from another thread.
[16七月2021 11:31:03.688] [Thread-54/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:572)
[16七月2021 11:31:03.691] [Thread-54/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactoryMixin.java:1163)
[16七月2021 11:31:03.692] [Thread-54/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactoryMixin.java:1149)
[16七月2021 11:31:03.694] [Thread-54/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.network.NetworkHooks.handler$bnm000$arclight$openContainer(NetworkHooksMixin.java:533)
[16七月2021 11:31:03.696] [Thread-54/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.network.NetworkHooks.openGui(NetworkHooksMixin.java:225)
[16七月2021 11:31:03.697] [Thread-54/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at dev.itsmeow.snailmail.block.entity.SnailBoxBlockEntity.lambda$openGUI$2(SnailBoxBlockEntity.java:162)
[16七月2021 11:31:03.699] [Thread-54/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Thread.run(Thread.java:748)
[16七月2021 11:31:03.898] [Thread-55/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.IllegalStateException: InventoryOpenEvent cannot be triggered asynchronously from another thread.
[16七月2021 11:31:03.900] [Thread-55/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:572)
[16七月2021 11:31:03.902] [Thread-55/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactoryMixin.java:1163)
[16七月2021 11:31:03.903] [Thread-55/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactoryMixin.java:1149)
[16七月2021 11:31:03.905] [Thread-55/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.network.NetworkHooks.handler$bnm000$arclight$openContainer(NetworkHooksMixin.java:533)
[16七月2021 11:31:03.907] [Thread-55/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.network.NetworkHooks.openGui(NetworkHooksMixin.java:225)
[16七月2021 11:31:03.912] [Thread-55/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at dev.itsmeow.snailmail.block.entity.SnailBoxBlockEntity.lambda$openGUI$2(SnailBoxBlockEntity.java:162)
[16七月2021 11:31:03.914] [Thread-55/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Thread.run(Thread.java:748)
[16七月2021 11:31:04.089] [Thread-56/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.IllegalStateException: InventoryOpenEvent cannot be triggered asynchronously from another thread.
[16七月2021 11:31:04.091] [Thread-56/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:572)
[16七月2021 11:31:04.093] [Thread-56/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactoryMixin.java:1163)
[16七月2021 11:31:04.095] [Thread-56/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactoryMixin.java:1149)
[16七月2021 11:31:04.097] [Thread-56/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.network.NetworkHooks.handler$bnm000$arclight$openContainer(NetworkHooksMixin.java:533)
[16七月2021 11:31:04.098] [Thread-56/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.network.NetworkHooks.openGui(NetworkHooksMixin.java:225)
[16七月2021 11:31:04.100] [Thread-56/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at dev.itsmeow.snailmail.block.entity.SnailBoxBlockEntity.lambda$openGUI$2(SnailBoxBlockEntity.java:162)
[16七月2021 11:31:04.101] [Thread-56/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Thread.run(Thread.java:748)
[16七月2021 11:31:04.294] [Thread-57/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.IllegalStateException: InventoryOpenEvent cannot be triggered asynchronously from another thread.
[16七月2021 11:31:04.296] [Thread-57/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:572)
[16七月2021 11:31:04.297] [Thread-57/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactoryMixin.java:1163)
[16七月2021 11:31:04.299] [Thread-57/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactoryMixin.java:1149)
[16七月2021 11:31:04.301] [Thread-57/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.network.NetworkHooks.handler$bnm000$arclight$openContainer(NetworkHooksMixin.java:533)
[16七月2021 11:31:04.303] [Thread-57/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.network.NetworkHooks.openGui(NetworkHooksMixin.java:225)
[16七月2021 11:31:04.304] [Thread-57/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at dev.itsmeow.snailmail.block.entity.SnailBoxBlockEntity.lambda$openGUI$2(SnailBoxBlockEntity.java:162)
[16七月2021 11:31:04.306] [Thread-57/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Thread.run(Thread.java:748)
[16七月2021 11:31:04.498] [Thread-58/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.IllegalStateException: InventoryOpenEvent cannot be triggered asynchronously from another thread.
[16七月2021 11:31:04.500] [Thread-58/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:572)
[16七月2021 11:31:04.501] [Thread-58/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactoryMixin.java:1163)
[16七月2021 11:31:04.503] [Thread-58/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactoryMixin.java:1149)
[16七月2021 11:31:04.505] [Thread-58/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.network.NetworkHooks.handler$bnm000$arclight$openContainer(NetworkHooksMixin.java:533)
[16七月2021 11:31:04.507] [Thread-58/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.network.NetworkHooks.openGui(NetworkHooksMixin.java:225)
[16七月2021 11:31:04.513] [Thread-58/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at dev.itsmeow.snailmail.block.entity.SnailBoxBlockEntity.lambda$openGUI$2(SnailBoxBlockEntity.java:162)
[16七月2021 11:31:04.514] [Thread-58/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Thread.run(Thread.java:748)
[16七月2021 11:31:04.702] [Thread-59/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.IllegalStateException: InventoryOpenEvent cannot be triggered asynchronously from another thread.
[16七月2021 11:31:04.703] [Thread-59/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:572)
[16七月2021 11:31:04.705] [Thread-59/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactoryMixin.java:1163)
[16七月2021 11:31:04.706] [Thread-59/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactoryMixin.java:1149)
[16七月2021 11:31:04.708] [Thread-59/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.network.NetworkHooks.handler$bnm000$arclight$openContainer(NetworkHooksMixin.java:533)
[16七月2021 11:31:04.710] [Thread-59/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.network.NetworkHooks.openGui(NetworkHooksMixin.java:225)
[16七月2021 11:31:04.712] [Thread-59/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at dev.itsmeow.snailmail.block.entity.SnailBoxBlockEntity.lambda$openGUI$2(SnailBoxBlockEntity.java:162)
[16七月2021 11:31:04.713] [Thread-59/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Thread.run(Thread.java:748)
[16七月2021 11:31:04.890] [Thread-60/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.IllegalStateException: InventoryOpenEvent cannot be triggered asynchronously from another thread.
[16七月2021 11:31:04.892] [Thread-60/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:572)
[16七月2021 11:31:04.894] [Thread-60/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactoryMixin.java:1163)
[16七月2021 11:31:04.896] [Thread-60/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactoryMixin.java:1149)
[16七月2021 11:31:04.897] [Thread-60/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.network.NetworkHooks.handler$bnm000$arclight$openContainer(NetworkHooksMixin.java:533)
[16七月2021 11:31:04.899] [Thread-60/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.network.NetworkHooks.openGui(NetworkHooksMixin.java:225)
[16七月2021 11:31:04.901] [Thread-60/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at dev.itsmeow.snailmail.block.entity.SnailBoxBlockEntity.lambda$openGUI$2(SnailBoxBlockEntity.java:162)
[16七月2021 11:31:04.903] [Thread-60/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by itsmeow** [comment]
Snail Mail is not compatible with Bukkit hybrid servers.
